// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Config holds the user's application settings.
 */
export class Config {
    "modelName": string;
    "modelsDir": string;
    "language": string;
    "translate": boolean;
    "hotkeyMod": string;
    "hotkeyKey": string;
    "microphoneId": string;
    "autoStart": boolean;

    /** Creates a new Config instance. */
    constructor($$source: Partial<Config> = {}) {
        if (!("modelName" in $$source)) {
            this["modelName"] = "";
        }
        if (!("modelsDir" in $$source)) {
            this["modelsDir"] = "";
        }
        if (!("language" in $$source)) {
            this["language"] = "";
        }
        if (!("translate" in $$source)) {
            this["translate"] = false;
        }
        if (!("hotkeyMod" in $$source)) {
            this["hotkeyMod"] = "";
        }
        if (!("hotkeyKey" in $$source)) {
            this["hotkeyKey"] = "";
        }
        if (!("microphoneId" in $$source)) {
            this["microphoneId"] = "";
        }
        if (!("autoStart" in $$source)) {
            this["autoStart"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Config instance from a string or object.
     */
    static createFrom($$source: any = {}): Config {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Config($$parsedSource as Partial<Config>);
    }
}
