// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * HistoryEntry represents a single transcription result.
 */
export class HistoryEntry {
    /**
     * Creates a new HistoryEntry instance.
     * @param {Partial<HistoryEntry>} [$$source = {}] - The source object to create the HistoryEntry.
     */
    constructor($$source = {}) {
        if (!("text" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["text"] = "";
        }
        if (!("timestamp" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["timestamp"] = 0;
        }
        if (!("language" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["language"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HistoryEntry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {HistoryEntry}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HistoryEntry(/** @type {Partial<HistoryEntry>} */($$parsedSource));
    }
}

/**
 * Preset holds settings for a single transcription preset.
 */
export class Preset {
    /**
     * Creates a new Preset instance.
     * @param {Partial<Preset>} [$$source = {}] - The source object to create the Preset.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("modelName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["modelName"] = "";
        }
        if (!("keepModelLoaded" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["keepModelLoaded"] = false;
        }
        if (!("inputMode" in $$source)) {
            /**
             * "hold" | "toggle"
             * @member
             * @type {string}
             */
            this["inputMode"] = "";
        }
        if (!("hotkey" in $$source)) {
            /**
             * "ctrl+shift+f1"
             * @member
             * @type {string}
             */
            this["hotkey"] = "";
        }
        if (!("language" in $$source)) {
            /**
             * "auto", "en", "ru"...
             * @member
             * @type {string}
             */
            this["language"] = "";
        }
        if (!("useKBLayout" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["useKBLayout"] = false;
        }
        if (!("keepHistory" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["keepHistory"] = false;
        }
        if (!("enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Preset instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Preset}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Preset(/** @type {Partial<Preset>} */($$parsedSource));
    }
}
