// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * HistoryService provides transcription history to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../internal/config/models.js";

/**
 * AddEntry saves a new transcription result.
 * @param {string} text
 * @param {string} language
 * @returns {$CancellablePromise<void>}
 */
export function AddEntry(text, language) {
    return $Call.ByID(9998647, text, language);
}

/**
 * ClearHistory removes all entries.
 * @returns {$CancellablePromise<void>}
 */
export function ClearHistory() {
    return $Call.ByID(1099722965);
}

/**
 * DeleteEntry removes an entry by timestamp.
 * @param {number} timestamp
 * @returns {$CancellablePromise<void>}
 */
export function DeleteEntry(timestamp) {
    return $Call.ByID(4096132091, timestamp);
}

/**
 * GetHistory returns all history entries (newest first).
 * @returns {$CancellablePromise<config$0.HistoryEntry[]>}
 */
export function GetHistory() {
    return $Call.ByID(4232163942).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * OpenHistoryWindow opens a separate window to display transcription history.
 * @returns {$CancellablePromise<void>}
 */
export function OpenHistoryWindow() {
    return $Call.ByID(1224997686);
}

// Private type creation functions
const $$createType0 = config$0.HistoryEntry.createFrom;
const $$createType1 = $Create.Array($$createType0);
