// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as SettingsService from "./settingsservice.js";
import * as TranscriptionService from "./transcriptionservice.js";
export {
    SettingsService,
    TranscriptionService
};
