// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * BackendInfo describes a compute backend and its availability.
 */
export class BackendInfo {
    /**
     * Creates a new BackendInfo instance.
     * @param {Partial<BackendInfo>} [$$source = {}] - The source object to create the BackendInfo.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("compiled" in $$source)) {
            /**
             * binary includes this backend (build tag)
             * @member
             * @type {boolean}
             */
            this["compiled"] = false;
        }
        if (!("systemAvailable" in $$source)) {
            /**
             * hardware + runtime present
             * @member
             * @type {boolean}
             */
            this["systemAvailable"] = false;
        }
        if (!("canInstall" in $$source)) {
            /**
             * hardware exists but runtime missing
             * @member
             * @type {boolean}
             */
            this["canInstall"] = false;
        }
        if (!("installHint" in $$source)) {
            /**
             * e.g. "CUDA Toolkit"
             * @member
             * @type {string}
             */
            this["installHint"] = "";
        }
        if (!("unavailableReason" in $$source)) {
            /**
             * "" | "no_hardware" | "no_driver" | "no_runtime" | "not_compiled"
             * @member
             * @type {string}
             */
            this["unavailableReason"] = "";
        }
        if (!("gpuDetected" in $$source)) {
            /**
             * e.g. "NVIDIA RTX 5070 Ti", ""
             * @member
             * @type {string}
             */
            this["gpuDetected"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BackendInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {BackendInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BackendInfo(/** @type {Partial<BackendInfo>} */($$parsedSource));
    }
}

/**
 * GlobalSettings holds non-preset settings.
 */
export class GlobalSettings {
    /**
     * Creates a new GlobalSettings instance.
     * @param {Partial<GlobalSettings>} [$$source = {}] - The source object to create the GlobalSettings.
     */
    constructor($$source = {}) {
        if (!("microphoneId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["microphoneId"] = "";
        }
        if (!("modelsDir" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["modelsDir"] = "";
        }
        if (!("theme" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["theme"] = "";
        }
        if (!("uiLang" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["uiLang"] = "";
        }
        if (!("closeAction" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["closeAction"] = "";
        }
        if (!("autoStart" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["autoStart"] = false;
        }
        if (!("startMinimized" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["startMinimized"] = false;
        }
        if (!("backend" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["backend"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GlobalSettings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {GlobalSettings}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GlobalSettings(/** @type {Partial<GlobalSettings>} */($$parsedSource));
    }
}

/**
 * LanguageInfo represents a supported transcription language.
 */
export class LanguageInfo {
    /**
     * Creates a new LanguageInfo instance.
     * @param {Partial<LanguageInfo>} [$$source = {}] - The source object to create the LanguageInfo.
     */
    constructor($$source = {}) {
        if (!("code" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["code"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LanguageInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LanguageInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LanguageInfo(/** @type {Partial<LanguageInfo>} */($$parsedSource));
    }
}

/**
 * MicrophoneInfo represents a capture device.
 */
export class MicrophoneInfo {
    /**
     * Creates a new MicrophoneInfo instance.
     * @param {Partial<MicrophoneInfo>} [$$source = {}] - The source object to create the MicrophoneInfo.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("isDefault" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isDefault"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MicrophoneInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MicrophoneInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MicrophoneInfo(/** @type {Partial<MicrophoneInfo>} */($$parsedSource));
    }
}

/**
 * ModelInfo describes a whisper model.
 */
export class ModelInfo {
    /**
     * Creates a new ModelInfo instance.
     * @param {Partial<ModelInfo>} [$$source = {}] - The source object to create the ModelInfo.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("fileName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["fileName"] = "";
        }
        if (!("size" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["size"] = "";
        }
        if (!("sizeBytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["sizeBytes"] = 0;
        }
        if (!("downloaded" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["downloaded"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ModelInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ModelInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ModelInfo(/** @type {Partial<ModelInfo>} */($$parsedSource));
    }
}

/**
 * ModelService manages whisper model files.
 */
export class ModelService {
    /**
     * Creates a new ModelService instance.
     * @param {Partial<ModelService>} [$$source = {}] - The source object to create the ModelService.
     */
    constructor($$source = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ModelService instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ModelService}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ModelService(/** @type {Partial<ModelService>} */($$parsedSource));
    }
}

/**
 * PresetState represents the recording state of a preset.
 */
export class PresetState {
    /**
     * Creates a new PresetState instance.
     * @param {Partial<PresetState>} [$$source = {}] - The source object to create the PresetState.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("state" in $$source)) {
            /**
             * "idle", "recording", "processing"
             * @member
             * @type {string}
             */
            this["state"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PresetState instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PresetState}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PresetState(/** @type {Partial<PresetState>} */($$parsedSource));
    }
}

/**
 * SystemInfo provides diagnostic system information.
 */
export class SystemInfo {
    /**
     * Creates a new SystemInfo instance.
     * @param {Partial<SystemInfo>} [$$source = {}] - The source object to create the SystemInfo.
     */
    constructor($$source = {}) {
        if (!("microphoneCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["microphoneCount"] = 0;
        }
        if (!("modelsCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["modelsCount"] = 0;
        }
        if (!("backends" in $$source)) {
            /**
             * @member
             * @type {BackendInfo[]}
             */
            this["backends"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SystemInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SystemInfo}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("backends" in $$parsedSource) {
            $$parsedSource["backends"] = $$createField2_0($$parsedSource["backends"]);
        }
        return new SystemInfo(/** @type {Partial<SystemInfo>} */($$parsedSource));
    }
}

/**
 * TranscriptionResult represents the result of a transcription operation.
 */
export class TranscriptionResult {
    /**
     * Creates a new TranscriptionResult instance.
     * @param {Partial<TranscriptionResult>} [$$source = {}] - The source object to create the TranscriptionResult.
     */
    constructor($$source = {}) {
        if (!("text" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["text"] = "";
        }
        if (!("error" in $$source)) {
            /**
             * empty if successful
             * @member
             * @type {string}
             */
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TranscriptionResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TranscriptionResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TranscriptionResult(/** @type {Partial<TranscriptionResult>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = BackendInfo.createFrom;
const $$createType1 = $Create.Array($$createType0);
