// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ModelService manages whisper model files.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CancelDownload cancels an in-progress download.
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function CancelDownload(name) {
    return $Call.ByID(1249064769, name);
}

/**
 * DeleteModel removes a downloaded model file.
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function DeleteModel(name) {
    return $Call.ByID(1023741701, name);
}

/**
 * DownloadModel downloads a model from HuggingFace with progress events.
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function DownloadModel(name) {
    return $Call.ByID(3559886972, name);
}

/**
 * GetAvailableModels returns the full catalog with download status.
 * @returns {$CancellablePromise<$models.ModelInfo[]>}
 */
export function GetAvailableModels() {
    return $Call.ByID(4218619458).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetModelsDir returns the current models directory path.
 * @returns {$CancellablePromise<string>}
 */
export function GetModelsDir() {
    return $Call.ByID(4112464074);
}

/**
 * ResolveModelsDir determines the models directory.
 * @returns {$CancellablePromise<string>}
 */
export function ResolveModelsDir() {
    return $Call.ByID(2847809866);
}

/**
 * SetModelsDir changes the models directory and optionally moves existing models.
 * @param {string} newDir
 * @param {boolean} moveModels
 * @returns {$CancellablePromise<void>}
 */
export function SetModelsDir(newDir, moveModels) {
    return $Call.ByID(4235632326, newDir, moveModels);
}

// Private type creation functions
const $$createType0 = $models.ModelInfo.createFrom;
const $$createType1 = $Create.Array($$createType0);
