// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * PresetService manages presets, recording, and transcription.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../internal/config/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CancelCapture cancels an in-progress key capture.
 * @returns {$CancellablePromise<void>}
 */
export function CancelCapture() {
    return $Call.ByID(647087517);
}

/**
 * CaptureHotkey blocks until the user presses a key/combo and returns it.
 * @returns {$CancellablePromise<string>}
 */
export function CaptureHotkey() {
    return $Call.ByID(466391173);
}

/**
 * CreatePreset adds a new preset and saves config.
 * @param {config$0.Preset} p
 * @returns {$CancellablePromise<config$0.Preset>}
 */
export function CreatePreset(p) {
    return $Call.ByID(3788349560, p).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * DeletePreset removes a preset.
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function DeletePreset(id) {
    return $Call.ByID(4181840091, id);
}

/**
 * GetLastText returns the last transcription result.
 * @returns {$CancellablePromise<string>}
 */
export function GetLastText() {
    return $Call.ByID(3603611038);
}

/**
 * GetModelLanguages returns available languages for a specific model.
 * @param {string} modelName
 * @returns {$CancellablePromise<$models.LanguageInfo[]>}
 */
export function GetModelLanguages(modelName) {
    return $Call.ByID(2508624501, modelName).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * GetPresets returns all presets.
 * @returns {$CancellablePromise<config$0.Preset[]>}
 */
export function GetPresets() {
    return $Call.ByID(3547733267).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * GetRecordingStates returns the state of all presets.
 * @returns {$CancellablePromise<$models.PresetState[]>}
 */
export function GetRecordingStates() {
    return $Call.ByID(4182724202).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * Init initializes audio and registers hotkeys for enabled presets.
 * @returns {$CancellablePromise<void>}
 */
export function Init() {
    return $Call.ByID(1658348945);
}

/**
 * ReorderPresets reorders presets to match the given ID order.
 * @param {string[]} ids
 * @returns {$CancellablePromise<void>}
 */
export function ReorderPresets(ids) {
    return $Call.ByID(227422882, ids);
}

/**
 * SetPresetEnabled enables or disables a preset (hotkey + model preloading).
 * @param {string} id
 * @param {boolean} enabled
 * @returns {$CancellablePromise<void>}
 */
export function SetPresetEnabled(id, enabled) {
    return $Call.ByID(2573940675, id, enabled);
}

/**
 * Shutdown releases all resources.
 * @returns {$CancellablePromise<void>}
 */
export function Shutdown() {
    return $Call.ByID(3481137245);
}

/**
 * StartRecording begins audio capture for a preset.
 * @param {string} presetID
 * @returns {$CancellablePromise<void>}
 */
export function StartRecording(presetID) {
    return $Call.ByID(3986860660, presetID);
}

/**
 * StopRecording stops capture and returns transcribed text.
 * @param {string} presetID
 * @returns {$CancellablePromise<$models.TranscriptionResult>}
 */
export function StopRecording(presetID) {
    return $Call.ByID(961787130, presetID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * UpdatePreset updates a preset and re-registers hotkeys/models only when needed.
 * @param {config$0.Preset} p
 * @returns {$CancellablePromise<void>}
 */
export function UpdatePreset(p) {
    return $Call.ByID(3151556069, p);
}

// Private type creation functions
const $$createType0 = config$0.Preset.createFrom;
const $$createType1 = $models.LanguageInfo.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $Create.Array($$createType0);
const $$createType4 = $models.PresetState.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = $models.TranscriptionResult.createFrom;
