// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SettingsService provides settings management to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../internal/config/models.js";

/**
 * GetSettings returns the current configuration.
 */
export function GetSettings(): $CancellablePromise<config$0.Config | null> {
    return $Call.ByID(2654852898).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * SaveSettings persists the configuration.
 */
export function SaveSettings(cfg: config$0.Config): $CancellablePromise<void> {
    return $Call.ByID(1510116317, cfg);
}

// Private type creation functions
const $$createType0 = config$0.Config.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
