// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SettingsService provides global settings management to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetAllBackends returns all known compute backends with availability info.
 * @returns {$CancellablePromise<$models.BackendInfo[]>}
 */
export function GetAllBackends() {
    return $Call.ByID(811517511).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetGlobalSettings returns the global (non-preset) settings.
 * @returns {$CancellablePromise<$models.GlobalSettings>}
 */
export function GetGlobalSettings() {
    return $Call.ByID(839432025).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * GetMicrophones returns available capture devices.
 * @returns {$CancellablePromise<$models.MicrophoneInfo[]>}
 */
export function GetMicrophones() {
    return $Call.ByID(1964778340).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * GetSystemInfo returns diagnostic information about the system.
 * @returns {$CancellablePromise<$models.SystemInfo>}
 */
export function GetSystemInfo() {
    return $Call.ByID(2463947982).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * InstallBackend installs the runtime for the given backend.
 * Returns "installed" if the package was installed directly,
 * "url" if a download page was opened in the browser.
 * @param {string} id
 * @returns {$CancellablePromise<string>}
 */
export function InstallBackend(id) {
    return $Call.ByID(2476532432, id);
}

/**
 * PickModelsDir opens a native directory picker dialog.
 * @returns {$CancellablePromise<string>}
 */
export function PickModelsDir() {
    return $Call.ByID(158629473);
}

/**
 * RestartApp launches a new instance of the application and quits the current one.
 * @returns {$CancellablePromise<void>}
 */
export function RestartApp() {
    return $Call.ByID(1502287031);
}

/**
 * SaveGlobalSettings saves the global settings.
 * @param {$models.GlobalSettings} gs
 * @returns {$CancellablePromise<void>}
 */
export function SaveGlobalSettings(gs) {
    return $Call.ByID(1855016490, gs);
}

// Private type creation functions
const $$createType0 = $models.BackendInfo.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.GlobalSettings.createFrom;
const $$createType3 = $models.MicrophoneInfo.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = $models.SystemInfo.createFrom;
