// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * TranscriptionService handles recording, transcription, and text output.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * IsRecording returns the current recording state.
 */
export function IsRecording(): $CancellablePromise<boolean> {
    return $Call.ByID(2858650925);
}

/**
 * StartRecording begins capturing audio from the microphone.
 */
export function StartRecording(): $CancellablePromise<void> {
    return $Call.ByID(1627800833);
}

/**
 * StopRecording stops capturing and returns the transcribed text.
 */
export function StopRecording(): $CancellablePromise<string> {
    return $Call.ByID(2858649025);
}
